service: serverless-aws
provider:
  name: aws

functions:
  run_rspec:
    runtime: ruby2.5
    handler: ruby/rspec_tester.RspecTester.call
    events:
      - http:
          path: rspec
          method: post

  run_jest:
    runtime: nodejs8.10
    handler: node/handler.run
    events:
      - http:
          path: jest
          method: post
